# Generated by Django 4.2.7 on 2026-04-14 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurse', '0001_initial'),
        ('teilnehmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmeldedatum', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Anmeldedatum')),
                ('status', models.CharField(choices=[('angemeldet', 'Angemeldet'), ('storniert', 'Storniert')], default='angemeldet', max_length=20, verbose_name='Status')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='kurse.kurs', verbose_name='Kurs')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='teilnehmer.teilnehmer', verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Anmeldung',
                'verbose_name_plural': 'Anmeldungen',
                'ordering': ['-anmeldedatum'],
                'indexes': [models.Index(fields=['kurs', 'status'], name='anmeldungen_kurs_id_6e4a9f_idx'), models.Index(fields=['teilnehmer'], name='anmeldungen_teilneh_84e8c1_idx')],
                'unique_together': {('kurs', 'teilnehmer')},
            },
        ),
    ]
