# Generated by Django 4.2.7 on 2026-04-14 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('start_datum', models.DateField(verbose_name='Startdatum')),
                ('end_datum', models.DateField(verbose_name='Enddatum')),
                ('max_teilnehmer', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximale Teilnehmerzahl')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurse',
                'ordering': ['-erstellt_am'],
                'indexes': [models.Index(fields=['titel'], name='kurse_kurs_titel_529790_idx'), models.Index(fields=['start_datum'], name='kurse_kurs_start_d_cb703d_idx')],
            },
        ),
    ]
