# Generated by Django 4.2.7 on 2026-04-14 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=50, verbose_name='Nachname')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Teilnehmer',
                'verbose_name_plural': 'Teilnehmer',
                'ordering': ['nachname', 'vorname'],
                'indexes': [models.Index(fields=['nachname', 'vorname'], name='teilnehmer__nachnam_56caf8_idx'), models.Index(fields=['email'], name='teilnehmer__email_e086c1_idx')],
            },
        ),
    ]
